### ISSUE TITLE
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException...

### ISSUE THREAD

**Issue by trigonometric-act** [capacitor-community/facebook-login#29] opened 2021-02-09 19:26 UTC
**Describe the bug**
After following all the steps as told I am receving this error

E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '277621683973226' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at ...

Why?

**Comment by rdlabo** [comment] 2021-02-10 07:43
What platform? ) web or iOS or Android. What method you use? I don't understand because there is too little information.
Please check [demo code](https://github.com/capacitor-community/facebook-login/tree/master/demo/angular)

**Comment by trigonometric-act** [comment] 2021-02-11 20:08
Hello and thank you for answer me.

I spent too many hours trying to make it work I finally lost my mind, sorry for the short info:

Platform: Android
Using: 
Ionic: 6.11.10
Angular: 9
Capacitor: 2.4.0
@capacitor-community/facebook-login: 1.1.0

I have an app on facebook developers which is in dev mode, with sha1 hashtag etc. And the same build gradle configuration you have in the sample that you passed me. 
I get this error E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException in android studio when finish building my app, and I can emulate my app but once I try to sign in:

  async signInFb(): Promise<void> {
  
    const FACEBOOK_PERMISSIONS = ['public_profile', 'email'];

    const result = await FacebookLogin.login({permissions: FACEBOOK_PERMISSIONS}).catch((err) => console.log(err));
    console.info('result 1', result);
}

Nothing happens and there is no call, If I switch my facebook developer app into production mode, error disappears but I can't sign. Also, when I am running the app I try to sign twice, second time I get overcalls error.

**Comment by trigonometric-act** [comment] 2021-02-11 22:18
Android Studio log after trying to sign in: 

V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 62467144, pluginId: FacebookLogin, methodName: login
V/Capacitor: callback: 62467144, pluginId: FacebookLogin, methodName: login, methodData: {"permissions":["public_profile","email"]}
D/Capacitor/FacebookLogin: Entering login()
I/Timeline: Timeline: Activity_launch_request time:52757940
D/Capacitor: App paused
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@17758f
D/CapacitorFirebaseAuth: Handle on Activity Result
    No saved call on activity result.

**Comment by trigonometric-act** [comment] 2021-02-11 22:36
I also get in logcat: 

W/com.facebook.UserSettingsManager: Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
2021-02-11 23:29:42.629 4219-4219/com.angularfirebase.comics W/com.facebook.UserSettingsManager: You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.

**Comment by trigonometric-act** [comment] 2021-02-11 22:37
And: 
2021-02-11 23:32:49.105 23769-32529/? E/fb4a.com.facebook.analytics.DeprecatedAnalyticsLogger: messaging_push_notif_fbns_lite is not allowed to log through legacy framework (https://fburl.com/69wk2eki). Please use USL fburl.com/usl.
2021-02-11 23:32:49.106 23769-5155/? W/fb4a.lacrima: Soft error detector missing: com.facebook.analytics.DeprecatedAnalyticsLogger messaging_push_notif_fbns_lite is not allowed to log through legacy framework (https://fburl.com/69wk2eki). Please use USL fburl.com/usl., delaying
2021-02-11 23:32:49.110 23769-32529/? E/fb4a.com.facebook.analytics.DeprecatedAnalyticsLogger: messaging_push_notif_fbns_lite is not allowed to log through legacy framework (https://fburl.com/69wk2eki). Please use USL fburl.com/usl.
2021-02-11 23:32:49.110 23769-5155/? W/fb4a.lacrima: Soft error detector missing: com.facebook.analytics.DeprecatedAnalyticsLogger messaging_push_notif_fbns_lite is not allowed to log through legacy framework (https://fburl.com/69wk2eki). Please use USL fburl.com/usl., delaying

**Comment by rdlabo** [comment] 2021-02-17 02:00
Sorry, I searched, but can not get this error in Android.

Did you try demo code? Others may be the cause of the error.

**Comment by rdlabo** [comment] 2021-03-05 08:14
Not received reply, so close it.
If you still have problems, please open a new one.

**Closed by rdlabo** 2021-03-05 08:14 UTC

**Comment by AmritRandhawaJi** [comment] 2021-08-06 12:34
Go To facebook developer account allow permissions that you have written in your code it works.
